import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import { defineConfig, globalIgnores } from 'eslint/config';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig([
  globalIgnores([
    'dist',
    'coverage',
    'playwright-report',
    'test-results',
    'blob-report',
    // Generated by `msw init` in Phase 2 — not ours to lint.
    'public/mockServiceWorker.js',
    // Generated by @tanstack/router-plugin from src/routes/**. Same reason.
    'src/routeTree.gen.ts',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      // Type-aware linting. Requires every linted file to belong to a tsconfig,
      // which is why tsconfig.app.json includes `test` and tsconfig.node.json
      // includes the config files and `e2e`.
      tseslint.configs.recommendedTypeChecked,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
      // Last: turns off everything Prettier owns.
      prettier,
    ],
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Same wording as rbs-backend/eslint.config.js — one rule, both repos.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Pairs with `verbatimModuleSyntax`: type-only imports must say so.
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
    },
  },
  {
    /*
     * Route files, where two rules disagree with the framework rather than
     * with us. Scoped to `src/routes/**` so neither is relaxed anywhere a real
     * component or a real throw lives.
     *
     * `react-refresh/only-export-components`: every route file must export a
     * `Route` object beside its component — that is TanStack's file-route
     * contract, and `@tanstack/router-plugin` handles Fast Refresh for these
     * files itself. The alternative is a disable comment on all forty of them,
     * growing by one per screen for the rest of the project.
     *
     * `@typescript-eslint/only-throw-error`: `throw redirect({ … })` is how the
     * router expresses "stop loading and go elsewhere" from `beforeLoad`.
     * `redirect()` returns a control-flow signal, not an `Error`, and the rule
     * is right in general — a thrown non-Error usually loses the stack. Here
     * the router catches it before it can.
     */
    files: ['src/routes/**/*.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
      '@typescript-eslint/only-throw-error': 'off',
    },
  },
  {
    // Node context, not browser.
    files: ['vite.config.ts', 'playwright.config.ts', 'e2e/**/*.ts'],
    languageOptions: { globals: globals.node },
  },
  {
    // This config file itself: linted, but not type-aware.
    files: ['**/*.{js,mjs,cjs}'],
    extends: [tseslint.configs.disableTypeChecked],
  },
]);
