import { createRouter } from '@tanstack/react-router';
import { routeTree } from '@/routeTree.gen';

/**
 * The router instance.
 *
 * `routeTree.gen.ts` is generated by `@tanstack/router-plugin` from
 * `src/routes/**` and is gitignored — it is derived, and a committed copy would
 * be a diff on every branch that adds a route. The plugin rebuilds it on `dev`
 * and on `build`, so a fresh clone produces it before anything imports it.
 */
export const router = createRouter({
  routeTree,

  /*
   * Preload on intent, not on render.
   *
   * `'intent'` fetches a route's chunk when the pointer lands on its link or it
   * takes focus — so a click feels instant without the console downloading all
   * forty screens on boot, which is exactly what §9 Phase 10's 250KB initial-JS
   * budget forbids.
   */
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,

  /*
   * Scroll to the top on navigation.
   *
   * The shell's scroll container is the `<main>` inside `AppShell`, not the
   * document, so the browser's own restoration has nothing to restore — without
   * this, moving from row 400 of a session list to a detail screen opens that
   * screen scrolled 400 rows down.
   */
  scrollRestoration: true,
});

/**
 * Teaches `Link`, `useNavigate`, and `useSearch` the real route tree.
 *
 * This is what makes `<Link to="/ops/playrs">` a compile error rather than a
 * 404 discovered by clicking — the reason §7.1 chose this router.
 */
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
