import { setupWorker } from 'msw/browser';
import { handlers } from '@/mocks/handlers';

/**
 * The mock network, in a browser.
 *
 * A service worker, which is what makes §1.4's claim true: MSW intercepts at
 * the network layer, so `api/client.ts` issues a real `fetch` and the
 * application code is byte-identical in mock and live mode. There is no mock
 * branch to forget to remove, and the requests show up in the Network tab where
 * an operator — or a reviewer checking that no token reaches `localStorage` —
 * can actually see them.
 *
 * `public/mockServiceWorker.js` is committed and generated by `npx msw init
 * public/`. It is excluded from ESLint and Prettier: it is MSW's file, not
 * ours, and reformatting it would make the next `msw init` a diff.
 */
export const worker = setupWorker(...handlers);

/**
 * Starts the worker, and resolves only once it is actually intercepting.
 *
 * Awaited before React mounts (`main.tsx`). Without that ordering the first
 * queries race the worker's registration and a few of them hit the real network
 * — which, in mock mode, is a 404 from the Vite dev server that looks exactly
 * like a broken endpoint.
 */
export async function startMockNetwork(): Promise<void> {
  await worker.start({
    // Anything not handled goes to the real network in silence. The console
    // loads fonts and source maps through the same layer, and warning on each
    // would bury a genuinely unhandled `/admin/v1` call in noise.
    onUnhandledRequest: (request, print) => {
      if (new URL(request.url).pathname.startsWith('/admin/')) print.warning();
    },
    quiet: true,
    serviceWorker: { url: '/mockServiceWorker.js' },
  });
}
